# Generated by Django 4.2.9 on 2026-03-03 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('radio_units_count', models.IntegerField(default=0)),
                ('alarms_critical_count', models.IntegerField(default=0)),
                ('alarms_major_count', models.IntegerField(default=0)),
                ('alarms_minor_count', models.IntegerField(default=0)),
                ('vswr_critical_count', models.IntegerField(default=0)),
                ('fru_count', models.IntegerField(default=0)),
                ('ret_count', models.IntegerField(default=0)),
                ('tma_count', models.IntegerField(default=0)),
                ('fiber_links_count', models.IntegerField(default=0)),
                ('sfp_modules_count', models.IntegerField(default=0)),
                ('pusch_cells_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Analisi',
                'verbose_name_plural': 'Analisi',
            },
        ),
        migrations.CreateModel(
            name='TMADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antenna_group', models.CharField(max_length=50)),
                ('antenna_near_unit', models.CharField(max_length=50)),
                ('radio_unit', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('device_type', models.CharField(max_length=50)),
                ('product_nr', models.CharField(blank=True, max_length=50)),
                ('revision', models.CharField(blank=True, max_length=20)),
                ('unique_id', models.CharField(blank=True, max_length=50)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tma_devices', to='core.analysis')),
            ],
            options={
                'verbose_name': 'TMA',
                'verbose_name_plural': 'TMA',
                'ordering': ['antenna_group', 'antenna_near_unit'],
            },
        ),
        migrations.CreateModel(
            name='SFPModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=50)),
                ('fru', models.CharField(max_length=50)),
                ('device_name', models.CharField(max_length=100)),
                ('tx_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rx_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('is_tn_backhaul', models.BooleanField(default=False)),
                ('is_rx_critical', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfp_modules', to='core.analysis')),
            ],
            options={
                'verbose_name': 'Modulo SFP',
                'verbose_name_plural': 'Moduli SFP',
                'ordering': ['port'],
            },
        ),
        migrations.CreateModel(
            name='RETDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antenna_group', models.CharField(max_length=50)),
                ('antenna_near_unit', models.CharField(max_length=50)),
                ('radio_unit', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('device_type', models.CharField(max_length=50)),
                ('product_nr', models.CharField(blank=True, max_length=50)),
                ('revision', models.CharField(blank=True, max_length=20)),
                ('unique_id', models.CharField(blank=True, max_length=50)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ret_devices', to='core.analysis')),
            ],
            options={
                'verbose_name': 'RET',
                'verbose_name_plural': 'RET',
                'ordering': ['antenna_group', 'antenna_near_unit'],
            },
        ),
        migrations.CreateModel(
            name='RadioUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fru', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=50)),
                ('rf_port', models.CharField(max_length=5)),
                ('branch_pair', models.CharField(max_length=10)),
                ('tx', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tx_unit', models.CharField(blank=True, max_length=10)),
                ('vswr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('return_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rx', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_vswr_warning', models.BooleanField(default=False)),
                ('is_vswr_critical', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_units', to='core.analysis')),
            ],
            options={
                'verbose_name': 'Radio Unit',
                'verbose_name_plural': 'Radio Units',
                'ordering': ['fru', 'rf_port'],
            },
        ),
        migrations.CreateModel(
            name='PuschData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=50)),
                ('sc', models.CharField(max_length=50)),
                ('fru', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=100)),
                ('pusch', models.DecimalField(decimal_places=1, max_digits=6)),
                ('pucch', models.DecimalField(decimal_places=1, max_digits=6)),
                ('port_a', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('port_b', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('port_c', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('port_d', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_rssi_high', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pusch_data', to='core.analysis')),
            ],
            options={
                'verbose_name': 'PUSCH/PUCCH',
                'verbose_name_plural': 'PUSCH/PUCCH',
                'ordering': ['cell'],
            },
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='logs/%Y/%m/%d/')),
                ('file_size', models.IntegerField(help_text='Dimensione file in bytes')),
                ('apparato_nome', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('sw_version', models.CharField(blank=True, max_length=50)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Log',
                'verbose_name_plural': 'File Log',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=100)),
                ('pmtemp', models.CharField(blank=True, max_length=20)),
                ('temp', models.IntegerField(blank=True, null=True)),
                ('upt', models.CharField(blank=True, max_length=50)),
                ('volt', models.CharField(blank=True, max_length=20)),
                ('sw', models.CharField(blank=True, max_length=100)),
                ('is_temp_high', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fru_units', to='core.analysis')),
            ],
            options={
                'verbose_name': 'FRU',
                'verbose_name_plural': 'FRU',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FiberLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50)),
                ('fru', models.CharField(max_length=50)),
                ('dl_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ul_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_dl_critical', models.BooleanField(default=False)),
                ('is_ul_critical', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiber_links', to='core.analysis')),
            ],
            options={
                'verbose_name': 'Link Fibra',
                'verbose_name_plural': 'Link Fibra',
                'ordering': ['link'],
            },
        ),
        migrations.CreateModel(
            name='BranchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fru', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=100)),
                ('rf_port', models.CharField(max_length=5)),
                ('branch_pair', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
                ('is_warning', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_pairs', to='core.analysis')),
            ],
            options={
                'verbose_name': 'Branch Pair',
                'verbose_name_plural': 'Branch Pairs',
                'ordering': ['fru', 'rf_port'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='log_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.logfile'),
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor')], max_length=10)),
                ('alarm_number', models.CharField(max_length=50)),
                ('cause', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.analysis')),
            ],
            options={
                'verbose_name': 'Allarme',
                'verbose_name_plural': 'Allarmi',
                'ordering': ['severity', 'alarm_number'],
            },
        ),
    ]
