# Generated by Django 4.2.9 on 2026-07-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_multifile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retdevice',
            name='revision',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tmadevice',
            name='revision',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tnbackhaul',
            name='revision',
            field=models.CharField(max_length=50),
        ),
    ]
