# Generated by Django 4.2.9 on 2026-03-13 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysis_user_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNBackhaul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=50)),
                ('lnh', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=10)),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_product', models.CharField(max_length=100)),
                ('revision', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('ericsson_product', models.CharField(max_length=100)),
                ('wavelength', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('tx_bias', models.CharField(blank=True, max_length=10, null=True)),
                ('tx_dbm', models.FloatField(blank=True, null=True)),
                ('rx_dbm', models.FloatField(blank=True, null=True)),
                ('is_rx_critical', models.BooleanField(default=False)),
                ('has_optical_data', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tn_backhaul', to='core.analysis')),
            ],
            options={
                'verbose_name': 'TN Backhaul',
                'verbose_name_plural': 'TN Backhaul Ports',
                'ordering': ['port'],
            },
        ),
    ]
