# Generated by Django 4.2.9 on 2026-03-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tnbackhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='fru',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fru',
            name='fault',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fru',
            name='lnh',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fru',
            name='maint',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fru',
            name='oper',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fru',
            name='product_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fru',
            name='rev',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fru',
            name='serial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fru',
            name='stat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fru',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
