# Generated by Django 4.2.9 on 2026-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expand_fru_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiberlink',
            options={'ordering': ['link_id'], 'verbose_name': 'Fiber Link', 'verbose_name_plural': 'Fiber Links'},
        ),
        migrations.RenameField(
            model_name='fiberlink',
            old_name='fru',
            new_name='ril',
        ),
        migrations.RemoveField(
            model_name='fiberlink',
            name='link',
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='is_link_down',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='link_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='link_status',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='rxdbm1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='rxdbm2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='temp1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='temp2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='txbs1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='txbs2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='txdbm1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='txdbm2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='wl1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fiberlink',
            name='wl2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
