# Generated by Django 4.2.9 on 2026-03-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_expand_fiber_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfpmodule',
            name='board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sfpmodule',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sfpmodule',
            name='ericsson_product',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sfpmodule',
            name='lnh',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sfpmodule',
            name='rev',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sfpmodule',
            name='ril',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sfpmodule',
            name='serial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sfpmodule',
            name='txbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sfpmodule',
            name='vendor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sfpmodule',
            name='wl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
