# Generated by Django 4.2.9 on 2026-04-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expand_sfp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LgaAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('severity', models.CharField(choices=[('C', 'Critical'), ('M', 'Major'), ('m', 'minor'), ('w', 'Warning'), ('*', 'Ceasing')], max_length=1)),
                ('specific_problem', models.CharField(max_length=500)),
                ('managed_object', models.CharField(blank=True, max_length=500)),
                ('additional_info', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lga_alarms', to='core.analysis')),
            ],
            options={
                'verbose_name': 'LGA Alarm',
                'verbose_name_plural': 'LGA Alarms',
                'ordering': ['timestamp'],
            },
        ),
    ]
