# Generated by Django 4.2.9 on 2026-05-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_lga_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fru', models.CharField(max_length=50)),
                ('alarm_port', models.IntegerField()),
                ('active_external_alarm', models.BooleanField(default=False)),
                ('administrative_state_code', models.CharField(blank=True, max_length=5)),
                ('administrative_state_label', models.CharField(blank=True, max_length=50)),
                ('alarm_slogan', models.CharField(blank=True, max_length=200)),
                ('normally_open', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_ports', to='core.analysis')),
            ],
            options={
                'verbose_name': 'Alarm Port',
                'verbose_name_plural': 'Alarm Ports',
                'ordering': ['fru', 'alarm_port'],
            },
        ),
    ]
