# Generated by Django 4.2.9 on 2026-05-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_alarm_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiounit',
            name='cell_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
